import { Prompt, Lora } from "next/font/google"; // 1. Import Lora เพิ่มเข้ามา
import "./globals.css";
import Navigation from "./components/Navigation";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "700"],
  variable: "--font-prompt", 
});

// 2. ตั้งค่าฟอนต์ Lora (ดึงสไตล์ italic มาทำเป็นสไตล์ลายเซ็น)
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"], // 400 จะได้เส้นที่บางเบากำลังสวยครับ
  style: ["italic"],       // ดึงเฉพาะตัวเอียงพริ้วๆ มาใช้งาน
  variable: "--font-lora", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // 3. ผูก variable ของ lora เข้าไปในระบบ
      className={`${prompt.variable} ${lora.variable} h-full antialiased`}>
      <body className={`${prompt.className} bg-gray-100`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
